Repository FoodShare-addinedu/FoodShare, pull requests merged in 2024-04, with the labels that each got.

#28 Feat/16 login page
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/index.js
  client/src/redux/store/reducer.js
  client/src/redux/store/store.js
  client/src/style/Global.scss
  client/src/style/style.scss
  client/src/views/auth/login/Login.jsx
  client/src/views/auth/login/Login.scss
  server/gradlew
Labels: 💎 [ FE ]

#34 feat: Header,Footer 전역 관리
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/router.js
  client/src/views/common/footer/Footer.jsx
  client/src/views/common/footer/Footer.scss
  client/src/views/common/header/Header.jsx
  client/src/views/common/header/Header.scss
Labels: ✨ Feat, 💎 [ FE ]

#37 feat : login token 처리 및 login form 구현
  client/src/views/auth/login/Login.jsx
  client/src/views/auth/login/Login.scss
Labels: ✨ Feat, 💎 [ FE ]

#47 feat: Main page 화면 구현
  client/src/App.js
  client/src/components/card/Cards.jsx
  client/src/style/Global.scss
  client/src/views/pages/main/Main.jsx
  client/src/views/pages/main/Main.scss
Labels: ✨ Feat, 💎 [ FE ]

#52 feat: Be_채팅 기능 구현
  server/build.gradle
  server/src/main/java/com/foodshare/chat/annotation/LogExecutionTime.java
  server/src/main/java/com/foodshare/chat/aspect/PerformanceAspect.java
  server/src/main/java/com/foodshare/chat/config/SecurityConfig.java
  server/src/main/java/com/foodshare/chat/config/WebConfig.java
  server/src/main/java/com/foodshare/chat/config/WebSocketConfig.java
  server/src/main/java/com/foodshare/chat/controller/ChatMessageController.java
  server/src/main/java/com/foodshare/chat/controller/ChatRoomController.java
  server/src/main/java/com/foodshare/chat/dto/ChatMessageDto.java
  server/src/main/java/com/foodshare/chat/dto/ChatRoomCreationDto.java
  server/src/main/java/com/foodshare/chat/dto/ChatRoomDto.java
  server/src/main/java/com/foodshare/chat/exception/ApplicationProcessingException.java
  server/src/main/java/com/foodshare/chat/exception/DatabaseServiceUnavailableException.java
  server/src/main/java/com/foodshare/chat/exception/DbErrorHandlingExecutor.java
  server/src/main/java/com/foodshare/chat/mapper/ChatDataMapper.java
  server/src/main/java/com/foodshare/chat/mapper/ChatDataMapperImpl.java
  server/src/main/java/com/foodshare/chat/repository/ChatMessageRepository.java
  server/src/main/java/com/foodshare/chat/repository/ChatRoomRepository.java
  server/src/main/java/com/foodshare/chat/repository/UserChatRoomVisibilityRepository.java
  server/src/main/java/com/foodshare/chat/service/ChatMessageService.java
  server/src/main/java/com/foodshare/chat/service/ChatRoomService.java
  server/src/main/java/com/foodshare/chat/utils/ValidationUtils.java
  server/src/main/java/com/foodshare/config/SecurityConfig.java
  server/src/main/java/com/foodshare/config/WebConfig.java
  server/src/main/java/com/foodshare/config/WebSocketConfig.java
  server/src/main/java/com/foodshare/domain/ChatMessage.java
  server/src/main/java/com/foodshare/domain/ChatRoom.java
  server/src/main/java/com/foodshare/domain/UserChatRoomVisibility.java
Labels: 🔙🔚 [ BE ]

#45 Feat/21 user login
  client/public/index.html
  client/src/views/auth/login/Login.jsx
  client/src/views/auth/login/Login.scss
  server/src/main/java/com/example/foodshare/jwt/SecurityConstants.java
  server/src/main/java/com/example/foodshare/jwt/domain/AuthenticationRequest.java
  server/src/main/java/com/example/foodshare/jwt/prop/JwtProp.java
  server/src/main/java/com/foodshare/security/controller/AdminController.java
  server/src/main/java/com/foodshare/security/controller/LoginController.java
  server/src/main/java/com/foodshare/security/controller/OTPController.java
  server/src/main/java/com/foodshare/security/controller/UserController.java
  server/src/main/java/com/foodshare/security/dto/CustomUserDetails.java
  server/src/main/java/com/foodshare/security/dto/CustomUserDetailsService.java
  server/src/main/java/com/foodshare/security/dto/EnrollUser.java
  server/src/main/java/com/foodshare/security/repository/UserRepository.java
  server/src/main/java/com/foodshare/security/service/LoginService.java
  server/src/main/java/com/foodshare/security/service/LoginServiceImpl.java
  server/src/main/java/com/foodshare/security/service/UserService.java
  server/src/main/java/com/foodshare/security/service/UserServiceImpl.java
  server/src/test/java/com/example/foodshare/controller/UserControllerTest_nickNameCheck.java
  server/src/test/java/com/example/foodshare/controller/UserControllerTest_register.java
  server/src/test/java/com/foodshare/controller/OTPControllerTest.java
  server/src/test/java/com/foodshare/controller/UserControllerTest_nickNameCheck.java
  server/src/test/java/com/foodshare/controller/UserControllerTest_register.java
  server/src/test/java/com/foodshare/jwt/controller/LoginControllerTest.java
Labels: 🔙🔚 [ BE ]

#59 feat: OnBoarding page 추가
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/img/onboarding01.svg
  client/public/img/onboarding02.svg
  client/public/img/onboarding03.svg
  client/src/App.js
  client/src/router.js
  client/src/style/Global.scss
  client/src/views/pages/onboarding/OnBoarding.jsx
  client/src/views/pages/onboarding/OnBoarding.scss
Labels: ✨ Feat, 💎 [ FE ]

#62 refactor: chat 서비스 세분화
  server/src/main/java/com/foodshare/chat/annotation/LogExecutionTime.java
  server/src/main/java/com/foodshare/chat/aspect/PerformanceAspect.java
  server/src/main/java/com/foodshare/chat/config/SecurityConfig.java
  server/src/main/java/com/foodshare/chat/config/WebConfig.java
  server/src/main/java/com/foodshare/chat/config/WebSocketConfig.java
  server/src/main/java/com/foodshare/chat/controller/ChatMessageController.java
  server/src/main/java/com/foodshare/chat/controller/ChatRoomController.java
  server/src/main/java/com/foodshare/chat/dto/ChatRoomDto.java
  server/src/main/java/com/foodshare/chat/mapper/ChatDataMapper.java
  server/src/main/java/com/foodshare/chat/mapper/ChatDataMapperImpl.java
  server/src/main/java/com/foodshare/chat/repository/ChatMessageRepository.java
  server/src/main/java/com/foodshare/chat/repository/ChatRoomRepository.java
  server/src/main/java/com/foodshare/chat/repository/UserChatRoomVisibilityRepository.java
  server/src/main/java/com/foodshare/chat/service/ChatMessageService.java
  server/src/main/java/com/foodshare/chat/service/ChatRoomMessageService.java
  server/src/main/java/com/foodshare/chat/service/ChatRoomService.java
  server/src/main/java/com/foodshare/chat/service/MessageProcessingService.java
  server/src/main/java/com/foodshare/chat/service/VisibilityService.java
  server/src/main/java/com/foodshare/chat/utils/ValidationUtils.java
Labels: ♻️ Refactor

#50 Feat: Chat Front _ 목록조회 , Stomp연결
  .gitattributes
  client/.gitignore
  client/config-overrides.js
  client/package.json
  client/src/router.js
  client/src/views/Chat/Chat.jsx
  client/src/views/Chat/Chat.scss
  client/src/views/Chat/ChatRoomList.jsx
  client/src/views/Chat/ChatRoomList.scss
  client/src/views/Chat/useChatDetailList.jsx
  client/src/views/Chat/useScrollManagement.jsx
  client/src/views/Chat/utils/throttle.js
Labels: 💎 [ FE ]

#66 feat: Mypage UI 구현
  client/package-lock.json
  client/package.json
  client/src/components/button/Button.jsx
  client/src/components/button/Button.scss
  client/src/components/list/List.jsx
  client/src/components/list/List.scss
  client/src/router.js
  client/src/views/pages/mypage/Mypage.jsx
  client/src/views/pages/mypage/Mypage.scss
Labels: ✨ Feat, 💎 [ FE ]

#64 Feat/57 fe sse 알림
  client/public/img/fooding.png
  client/public/img/userImage.png
  client/src/views/Notification/NotificationMessage.jsx
  client/src/views/Notification/NotificationMessage.scss
  client/src/views/Notification/SSEComponent.jsx
  client/src/views/Notification/useSSEConnection.jsx
  client/src/views/Notification/utils/isTokenValid.jsx
Labels: ✨ Feat, 💎 [ FE ]

#63 Feat/55 be sse 기본 알림
  server/src/main/java/com/foodshare/chat/service/ChatRoomService.java
  server/src/main/java/com/foodshare/chat/utils/ValidationUtils.java
  server/src/main/java/com/foodshare/domain/Notification.java
  server/src/main/java/com/foodshare/notification/repository/NotificationRepository.java
  server/src/main/java/com/foodshare/notification/service/NotificationService.java
  server/src/main/java/com/foodshare/notification/sse/component/SseEmitters.java
  server/src/main/java/com/foodshare/notification/sse/controller/SseController.java
  server/src/main/java/com/foodshare/notification/sse/service/SseEmitterService.java
Labels: 🔙🔚 [ BE ], ✨ Feat

#69 feat: login 유효성검사 추가
  client/public/img/cookshare.svg
  client/src/router.js
  client/src/style/Global.scss
  client/src/views/auth/login/Login.jsx
  client/src/views/auth/login/Login.scss
Labels: ✨ Feat, 💎 [ FE ]

#72 Feat/32 be food update delete
  server/src/main/java/com/foodshare/board/controller/FoodApiController.java
  server/src/main/java/com/foodshare/board/exception/GlobalExceptionHandler.java
  server/src/main/java/com/foodshare/board/repository/FoodRepository.java
  server/src/main/java/com/foodshare/board/service/FileStorageService.java
  server/src/main/java/com/foodshare/board/service/FoodService.java
  server/src/main/resources/logback-spring.xml
Labels: 🔙🔚 [ BE ], ✨ Feat

#73 Feat/70 be fe seach
  client/src/App.js
  client/src/views/pages/main/ErrorBoundary.jsx
  client/src/views/pages/main/Main.jsx
  client/src/views/pages/main/Main.scss
  client/src/views/pages/main/MainDetail.jsx
  client/src/views/pages/main/MainDetail.scss
  client/src/views/pages/main/MainForm.jsx
  client/src/views/pages/main/MainForm.scss
  server/src/main/java/com/foodshare/board/controller/FoodApiController.java
  server/src/main/java/com/foodshare/board/repository/FoodRepository.java
  server/src/main/java/com/foodshare/board/service/FoodService.java
  server/src/main/java/com/foodshare/domain/User.java
  server/src/main/java/com/foodshare/security/controller/LoginController.java
  server/src/main/java/com/foodshare/security/dto/CustomUserDetails.java
  server/src/main/java/com/foodshare/security/jwt/SecurityConstants.java
  server/src/main/java/com/foodshare/security/jwt/domain/AuthenticationRequest.java
  server/src/main/java/com/foodshare/security/jwt/prop/JwtProp.java
Labels: ❓ question, 🔙🔚 [ BE ], ✨ Feat, 💎 [ FE ]

#75 feat: Register page 구현
  client/package.json
  client/src/components/adress/Adress.jsx
  client/src/components/adress/useKakaoLoader.js
  client/src/hook/useDebounce.js
  client/src/router.js
  client/src/views/auth/register/Register.jsx
  client/src/views/auth/register/Register.scss
Labels: ✨ Feat, 💎 [ FE ]

#79 Refactor/78 chat refactor be
  server/src/main/java/com/foodshare/chat/controller/ChatMessageController.java
  server/src/main/java/com/foodshare/chat/controller/ChatRoomController.java
  server/src/main/java/com/foodshare/chat/dto/ChatRequstDto.java
  server/src/main/java/com/foodshare/chat/exception/ApplicationProcessingException.java
  server/src/main/java/com/foodshare/chat/exception/DatabaseServiceUnavailableException.java
  server/src/main/java/com/foodshare/chat/exception/DbErrorHandlingExecutor.java
  server/src/main/java/com/foodshare/chat/service/ChatRoomMessageService.java
  server/src/main/java/com/foodshare/chat/service/ChatRoomService.java
  server/src/main/java/com/foodshare/chat/service/MessageProcessingService.java
  server/src/main/java/com/foodshare/chat/utils/ValidationUtils.java
Labels: 🔙🔚 [ BE ], ♻️ Refactor

#81 refactor:chat_fe 시큐리티 경로 적용및 , 데이터 전송 구조 변경
  client/src/views/Chat/Chat.jsx
  client/src/views/Chat/ChatRoomList.jsx
  client/src/views/Chat/ChatRoomList.scss
  client/src/views/Chat/useChatDetailList.jsx
  client/src/views/Chat/useScrollManagement.jsx
  client/src/views/Chat/useWebSocketConnection.jsx
  client/src/views/Chat/utils/throttle.js
Labels: 💎 [ FE ], ♻️ Refactor

#83 refactor: 알림 분리 _be
  server/src/main/java/com/foodshare/notification/notificationutils/ExecutorConfig.java
  server/src/main/java/com/foodshare/notification/repository/NotificationRepository.java
  server/src/main/java/com/foodshare/notification/service/NotificationAggregator.java
  server/src/main/java/com/foodshare/notification/service/NotificationService.java
  server/src/main/java/com/foodshare/notification/sse/controller/SseController.java
  server/src/main/java/com/foodshare/notification/sse/service/HeartbeatService.java
  server/src/main/java/com/foodshare/notification/sse/service/SseEmitterService.java
Labels: 🔙🔚 [ BE ], ♻️ Refactor

#88 feat: Header, Footer 컴포넌트에 필요한 기능 구현
  client/package.json
  client/src/components/adress/Address.jsx
  client/src/components/adress/Adress.jsx
  client/src/index.js
  client/src/redux/addressSlice.js
  client/src/redux/store.js
  client/src/redux/store/reducer.js
  client/src/redux/store/store.js
  client/src/router.js
  client/src/style/Global.scss
  client/src/style/style.scss
  client/src/views/auth/register/Register.jsx
  client/src/views/common/footer/Footer.jsx
  client/src/views/common/footer/Footer.scss
  client/src/views/common/header/Header.jsx
  client/src/views/common/header/Header.scss
  client/src/views/pages/search/Search.jsx
  client/src/views/pages/search/Search.scss
  client/src/views/pages/searchaddress/SearchAddress.jsx
Labels: ✨ Feat, 💎 [ FE ]

#92 feat: 토큰에 id, location, nickname 포함해서 발행 #91
  server/build.gradle
  server/src/main/java/com/foodshare/security/controller/RegisterRequest.java
  server/src/main/java/com/foodshare/security/dto/CustomUserDetails.java
  server/src/main/java/com/foodshare/security/dto/CustomUserDetailsService.java
  server/src/main/java/com/foodshare/security/jwt/AuthenticationRequest.java
  server/src/main/java/com/foodshare/security/jwt/JwtAuthenticationFilter.java
  server/src/main/java/com/foodshare/security/jwt/JwtAuthorizationFilter.java
  server/src/main/java/com/foodshare/security/jwt/JwtProp.java
  server/src/main/java/com/foodshare/security/jwt/JwtUtil.java
  server/src/main/java/com/foodshare/security/jwt/SecurityConstants.java
  server/src/main/java/com/foodshare/security/service/RedisService.java
Labels: 🔙🔚 [ BE ], ✨ Feat

#90 feat: 주소 API bottom popup 처리
  client/src/components/adress/Adress.jsx
  client/src/components/drawer/AddressDrawer.jsx
  client/src/views/auth/register/Register.jsx
  client/src/views/auth/register/Register.scss
Labels: ✨ Feat, 💎 [ FE ]

#94 feat: 토큰 재발급, 로그아웃 토큰 관리
  server/src/main/java/com/foodshare/security/config/WebSecurityConfig.java
  server/src/main/java/com/foodshare/security/controller/LoginController.java
  server/src/main/java/com/foodshare/security/controller/LogoutController.java
  server/src/main/java/com/foodshare/security/jwt/JwtAuthenticationFilter.java
  server/src/main/java/com/foodshare/security/jwt/JwtAuthorizationFilter.java
  server/src/main/java/com/foodshare/security/jwt/JwtUtil.java
  server/src/main/java/com/foodshare/security/service/RedisService.java
Labels: 🔙🔚 [ BE ], ✨ Feat

#86 Refactor/84 알림 분리 fe
  client/src/views/Notification/NotificationMessage.jsx
  client/src/views/Notification/NotificationMessage.scss
  client/src/views/Notification/SSEComponent.jsx
  client/src/views/Notification/useSSEConnection.jsx
  client/src/views/Notification/utils/isTokenValid.jsx
Labels: 💎 [ FE ], ♻️ Refactor

#97 Feat/76 main page
  client/public/img/locationdot.svg
  client/src/App.js
  client/src/components/adress/MapView.jsx
  client/src/components/adress/MapView.scss
  client/src/components/badge/Badge.jsx
  client/src/components/badge/Badge.scss
  client/src/components/button/Button.jsx
  client/src/components/button/Button.scss
  client/src/components/card/Cards.jsx
  client/src/components/card/Cards.scss
  client/src/components/caution/Caution.jsx
  client/src/components/drawer/Drawers.jsx
  client/src/components/select/Select.jsx
  client/src/components/select/Select.scss
  client/src/data/CautionData.js
  client/src/router.js
  client/src/style/Global.scss
  client/src/views/common/footer/Footer.scss
  client/src/views/common/header/Header.scss
  client/src/views/pages/main/Main.jsx
  client/src/views/pages/main/Main.scss
  client/src/views/pages/main/MainDetail.jsx
  client/src/views/pages/main/MainDetail.scss
  client/src/views/pages/main/MainForm.jsx
  client/src/views/pages/main/MainForm.scss
  client/src/views/pages/mypage/Mypage.scss
  client/src/views/pages/onboarding/OnBoarding.jsx
  client/src/views/pages/onboarding/OnBoarding.scss
  client/src/views/pages/searchaddress/SearchAddress.jsx
Labels: 🐛 Bug, ✨ Feat, 💎 [ FE ], ⚙️ Setting, ♻️ Refactor

#103 Feat/102 알림 미확인목록조회be
  server/src/main/java/com/foodshare/notification/controller/NotificationController.java
  server/src/main/java/com/foodshare/notification/dto/NotificationDto.java
  server/src/main/java/com/foodshare/notification/repository/NotificationRepository.java
  server/src/main/java/com/foodshare/notification/service/NotificationService.java
  server/src/main/java/com/foodshare/notification/sse/component/SseEmitters.java
  server/src/main/java/com/foodshare/notification/sse/controller/SseController.java
  server/src/main/java/com/foodshare/notification/sse/service/SseEmitterService.java
Labels: 🔙🔚 [ BE ], ✨ Feat

#99 feat:98/채팅목록 미확인 메시지 전부 조회
  server/src/main/java/com/foodshare/chat/annotation/LogExecutionTime.java
  server/src/main/java/com/foodshare/chat/aspect/PerformanceAspect.java
  server/src/main/java/com/foodshare/chat/controller/ChatMessageController.java
  server/src/main/java/com/foodshare/chat/controller/ChatRoomController.java
  server/src/main/java/com/foodshare/chat/dto/ChatRoomCreateRequest.java
  server/src/main/java/com/foodshare/chat/dto/ChatRoomCreationDto.java
  server/src/main/java/com/foodshare/chat/exception/ApplicationProcessingException.java
  server/src/main/java/com/foodshare/chat/exception/DatabaseServiceUnavailableException.java
  server/src/main/java/com/foodshare/chat/mapper/ChatDataMapperImpl.java
  server/src/main/java/com/foodshare/chat/repository/ChatRoomRepository.java
  server/src/main/java/com/foodshare/chat/service/ChatRoomMessageService.java
  server/src/main/java/com/foodshare/chat/service/ChatRoomService.java
  server/src/main/java/com/foodshare/chat/service/MessageProcessingService.java
  server/src/main/java/com/foodshare/chat/service/MongoQueryBuilder.java
  server/src/main/java/com/foodshare/chat/service/VisibilityService.java
Labels: 🔙🔚 [ BE ], ✨ Feat

#101 feat: 채팅 미확인 메시지 조회 기능
  client/src/router.js
  client/src/views/Chat/Chat.jsx
  client/src/views/Chat/Chat.scss
  client/src/views/Chat/ChatButton.jsx
  client/src/views/Chat/ChatRoomList.jsx
  client/src/views/Chat/ChatRoomList.scss
  client/src/views/Chat/useChatDetailList.jsx
  client/src/views/Chat/useScrollManagement.jsx
  client/src/views/common/footer/Footer.jsx
Labels: ✨ Feat, 💎 [ FE ]
